### ISSUE TITLE
Reification, unexpected returned value

### ISSUE THREAD

**Issue by cprudhom** [ibex-team/ibex-java#2]
Hi,

I experience what I consider as an issue which can be reproduced with the following code:
```java
Ibex ibex = new Ibex(new double[]{0.01});
ibex.add_ctr("{0}=59.5");
ibex.build();
double domains[] = {59.5, 59.5};
Assert.assertEquals(ibex.contract(0, domains, 0), Ibex.FAIL);
// OR
// Assert.assertEquals(ibex.contract(0, domains, 1), Ibex.ENTAILED);
ibex.release();
```
But (in both case) I got `Ibex.NOTHING` as returned value. 
Could you help me?

**Comment by gchabert** [comment]
If the reifification argument 1, it returns NOTHING because nothing can be removed from the domain. I guess that is OK for you.
If the argument is 0, it returns NOTHING because we don't handle negation constraints (x<>y) in Ibex. Remind that this constraint has barely no sense with continuous domains. In particular, it is impossible to have a domain entailed for a negation constraint except on very particular cases like x=y. This brings us back to a recent discussion https://github.com/ibex-team/ibex-lib/issues/435  (see my answer to your posts in March, 18).

**Comment by cprudhom** [comment]
Thank you for the answer and the reminder. I always miss that point with continuous domains (I will do my best to not forgot that point in the future).
There are certainly cases which can be handle natively with Choco. It needs further investigation and development though.

**Comment by cprudhom** [comment]
> If the reifification argument 1, it returns NOTHING because nothing can be removed from the domain. I guess that is OK for you.
> If the argument is 0, it returns NOTHING because we don't handle negation constraints (x<>y) in Ibex. Remind that this constraint has barely no sense with continuous domains. In particular, it is impossible to have a domain entailed for a negation constraint except on very particular cases like x=y. This brings us back to a recent discussion [ibex-team/ibex-lib#435](https://github.com/ibex-team/ibex-lib/issues/435) (see my answer to your posts in March, 18).

**Comment by gchabert** [comment]
No worry!
